[tasks.wasm-pack]
command = "wasm-pack"
args = [ "build", "--target=web", "--release" ]

[tasks.wasm-dist]
description = '''
Build wasm without to be published. Clean, build and
remove .gitignore from `./pkg/` after build.
'''
script = [ "rm -r ../pkg", "mv ./pkg ..", "rm ../pkg/.gitignore", "cp ./index.html .." ]
dependencies = [ "wasm-pack" ]